name: Docker Image CI

env:
  REPO_URL: https://github.com/felix-ls/IberiaEyen2.git
  REPO_BRANCH: main

on:
  repository_dispatch:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    steps: 
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Git Clone 
        run: |
          git clone --depth 1 $REPO_URL -b $REPO_BRANCH IberiaEye
          sed -i "s#baseURL: '.*/'#baseURL: 'http://127.0.0.1:2000/'#g" IberiaEye/nuxt.config.js
        
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 7
          run_install: |
            - cwd: ./IberiaEye
      
      - name: Build
        run: cd IberiaEye && pnpm run build

      - name: Get version
        id: get_version
        run: echo VERSION=$(date +%F) >> $GITHUB_OUTPUT

      - name: Docker Setup QEMU
        uses: docker/setup-qemu-action@v3
      - name: Docker Setup Buildx
        uses: docker/setup-buildx-action@v3

      - name: Docker Login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
        
      - name: Build and push Docker images
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: linux/amd64,linux/arm64,linux/arm
          push: true
#          tags: ${{ secrets.USERNAME }}/iberiaeye,${{ secrets.USERNAME }}/iberiaeye:vant,${{ secrets.USERNAME }}/iberiaeye:${{ steps.get_version.outputs.VERSION }}
          tags: ${{ secrets.USERNAME }}/iberiaeye:main,${{ secrets.USERNAME }}/iberiaeye:${{ steps.get_version.outputs.VERSION }}
          
